package common;

 public enum ResultMessage {
	 LOGIN_SUCCESSFULLY,
	 LOGIN_FAILED,
	 INVALID_ID_OR_PASSWORD,
	 NO_ACCOUNT,
	 ENTER_COOPROOM_SUCCEDDFULLY,
	 ENTER_COOPROOM_FAILED,
	 QUIT_COOPROOM_SUCCESSFULLY,
	 QUIT_COOPROOM_FAILED,
	 SET_READY_SUCCESSFULLY,
	 SET_READY_FALIED
}
