package common;

 public enum ResultMessage {
	 LOGIN_SUCCESSFULLY,
	 LOGIN_FAILED,
	 DUPLICATE_ACCOUNT_LOGIN,
	 REGISTER_SUCCESSFULLY,
	 REGISTER_FAILED,
	 CHANGE_PASSWORD_SUCCESSFULLY,
	 CHANGE_PASSWORD_FAILED,
	 INVALID_ID_OR_PASSWORD,
	 NO_ACCOUNT,
	 ENTER_COOPROOM_SUCCEDDFULLY,
	 ENTER_COOPROOM_FAILED,
	 ENTER_BATTLEROOM_SUCCEDDFULLY,
	 ENTER_BATTLEROOM_FAILED,
	 QUIT_COOPROOM_SUCCESSFULLY,
	 QUIT_COOPROOM_FAILED,
	 QUIT_BATTLEROOM_SUCCESSFULLY,
	 QUIT_BATTLEROOM_FAILED,
	 SET_READY_SUCCESSFULLY,
	 SET_READY_FALIED,
	 CHANGE_TEAM_SUCCESSFULLY,
	 CHANGE_TEAM_FAILED
}
